### ISSUE TITLE
Verificação dos arquivos

### ISSUE THREAD

**Issue by Raygagz** [mazucanti/PrOOjeto#15]
Precisamos definir onde iremos checar se os arquivos estão vazios para gerar um cabeçalho.

   Podemos fazer isso em vários lugares, na parte de cadastro, login, agenda, nos construtores ou no main.

   É uma verificação única e só necessária na primeira vez que formos tentar abrir um arquivo da databse

**Comment by mazucanti** [comment]
Eu vou tentar dar uma olhada nos códigos e tentar mudar o mínimo possível do que tá feito
